# cuda-vector-add.yaml
apiVersion: v1
kind: Pod
metadata:
 name: openface-cuda3
 namespace: nvidia
spec:
 restartPolicy: OnFailure
 containers:
   - name: openface-cuda3
     image: "mandog/openface_cuda"
     serviceAccountName: useroot
     env:
       - name: NVIDIA_VISIBLE_DEVICES
         value: all
       - name: NVIDIA_DRIVER_CAPABILITIES
         value: "compute,utility"
       - name: NVIDIA_REQUIRE_CUDA
         value: "cuda>=8.0"
     resources:
       limits:
         nvidia.com/gpu: 1 # requesting 1 GPU
     nodeSelector:
       openshift.com/gpu-accelerator: true
