apiVersion: v1
kind: Service
metadata:
  labels:
    app: mec-caching-server
  name: mec-caching-server
spec:
  selector:
    app: mec-caching-server
  ports:
  - nodePort: 0
    port: 80
    protocol: TCP
    targetPort: 80


---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: mec-caching-server
  name: mec-caching-server
  namespace: hls-demo
spec:
  replicas: 1
  selector:
    app: mec-caching-server
    deploymentconfig: mec-caching-server
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: mec-caching-server
        deploymentconfig: mec-caching-server
    spec:
      containers:
        - image: >-
            mandog/nginx_cache_server_web_demo
          imagePullPolicy: Always
          name: mec-caching-server
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: useroot
      serviceAccountName: useroot
      terminationGracePeriodSeconds: 30
  test: false

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: mec-caching-server
  name: mec-caching-server
  namespace: hls-demo
spec:
  host: mec-caching-server-hls-demo.apps.172.18.2.132.nip.io
  to:
    kind: Service
    name: mec-caching-server
    weight: 100
  wildcardPolicy: None
