version: '2'

services:
  app:
    image: vlc_img
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
     - DISPLAY
    volumes:
     - /tmp/.X11-unix
    command: bash -c "sed -i 's/geteuid/getppid/' /usr/bin/vlc && vlc -q --no-autoscale --zoom 0.8 --qt-minimal-view --no-audio --no-qt-privacy-ask http://172.18.3.227/hls/sample9.m3u8"
